language: c
script: asdf plugin test editorconfig-checker $TRAVIS_BUILD_DIR 'ec --version'
before_script:
  - git clone https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh
os:
  - linux
  - osx
